# Generated by Django 6.0.2 on 2026-03-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_attribute_attributevalue_productimage_productvariant_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_price_9b1a5f_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
