# Generated by Django 6.0.2 on 2026-03-22 18:21

import products.services.file_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_products_pr_price_9b1a5f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.services.file_upload.get_product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.services.file_upload.get_product_variant_image_upload_path),
        ),
    ]
