# Generated by Django 6.0.2 on 2026-03-22 18:21

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_products_pr_price_9b1a5f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.storage.UploadPath('products', 'product_id')),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.storage.UploadPath('product_variant', 'variant_id')),
        ),
    ]
